### ISSUE TITLE
Natural language query generation support ?

### ISSUE THREAD

**Issue by ms-semarchy** [terraform-aws-modules/terraform-aws-opensearch#28]
It seems the module does not support it yet because this is a new AWS feature :

<img width="702" alt="Screenshot 2024-10-08 at 16 40 16" src="https://github.com/user-attachments/assets/327f2ec2-cf15-41d0-bbab-9b263fff9c05">

**Comment by bryantbiggs** [comment]
please see the issue template - it asks if the AWS provider supports this. We can't support something that is not in the provider
